# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05a9949ddf982e57275b7549656ae45edd5c81b0a78e8f701217615b95f033ae061deba7b83368e1382dd5b7aef52413b38bd7b58e3550e8aedea5c8440e2902

test:
  secret_key_base: 6e969fba6dfd74813b81a76bcf4f0f59bb8e377d1cd6ce41e3c333582f4cf789338bd110284578c27bc48368065acac728be47a8344af58cddc49f9f0fb8f6b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
